cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:painting_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:painting_id>/', views.cart_remove, name='cart_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

picture_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('order.urls', namespace='order')),
    path('', include('shop.urls', namespace='shop')),
] + debug_toolbar_urls()

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.painting_list, name='painting_list'),
    path('<slug:tag_slug>/', views.painting_list,
         name='painting_list_by_tag'),
    path('<int:id>/<slug:slug>/', views.painting_detail,
         name='painting_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from shop.models import Painting


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(painting.get_cost() for painting in self.paintings.all())


class OrderPainting(models.Model):
    order = models.ForeignKey(Order,
                              related_name='paintings',
                              on_delete=models.CASCADE)

    painting = models.ForeignKey(Painting,
                                 related_name='order_paintings',
                                 on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price

shop/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=200, verbose_name='Назавание')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Slug')

    class Meta:
        ordering = ['name']

        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:painting_list_by_tag', args=(self.slug,))


class Painting(models.Model):
    tag = models.ManyToManyField(Tag, related_name='paintings', verbose_name='Теги')
    name = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='pictures/%Y/%m/%d', blank=True, verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='В наличии')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Изменено')

    class Meta:
        ordering = ['name']

        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:painting_detail', args=(self.pk, self.slug,))

cart/forms.py
from django import forms

# PAINTING_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


# class CartAddPaintingForm(forms.Form):
#     quantity = forms.TypedChoiceField(
#         choices=PAINTING_QUANTITY_CHOICES,
#         coerce=int)
#     override = forms.BooleanField(required=False,
#                                   initial=False,
#                                   widget=forms.HiddenInput)

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

cart/views.py
import redis

from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Painting
from .cart import Cart
from shop.recommender_system import most_view


@require_POST
def cart_add(request, painting_id):
    cart = Cart(request)
    painting = get_object_or_404(Painting, id=painting_id)
    cart.add(painting=painting)
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, painting_id):
    cart = Cart(request)
    painting = get_object_or_404(Painting, id=painting_id)
    cart.remove(painting)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    cart_paintings = [item['painting'] for item in cart]
    exclude_list = [painting.id for painting in cart_paintings]
    return render(request, 'cart/detail.html', {'cart': cart, 'most_view': most_view(exclude_list)})

order/views.py
from django.shortcuts import render
from .models import OrderPainting
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderPainting.objects.create(order=order,
                                             painting=item['painting'],
                                             price=item['price'],
                                             )

            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})

shop/views.py
import redis

from django.shortcuts import render, get_object_or_404

from .models import Painting, Tag
from .recommender_system import most_view, increase_rating



def painting_list(request, tag_slug=None):
    tag = None
    tags = Tag.objects.all()
    paintings = Painting.objects.filter(available=True)
    if tag_slug:
        tag = get_object_or_404(Tag,
                                slug=tag_slug)
        paintings = paintings.filter(tag=tag)
    return render(request,
                  'shop/painting/list.html',
                  {'tag': tag,
                   'tags': tags, 'paintings': paintings})


def painting_detail(request, id, slug):
    painting = get_object_or_404(Painting, id=id, slug=slug)
    increase_rating(painting.id)
    exclude_list = [painting.id]
    return render(request, 'shop/painting/detail.html',
                  {'painting': painting, 'most_view': most_view(exclude_list)})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<div class="checkout">
    <h1>Your shopping cart</h1>
    <table class="cart">
        <tbody>
        {% for item in cart %}
        {% with painting=item.painting %}
        <tr>
            <td>
                <a href="{{ painting.get_absolute_url }}">
                    <img src="{% if painting.image %}{{ painting.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
            </td>
            <td>{{ painting.name }}</td>
            <td class="num">{{ item.price }} руб.</td>
            <td>
                <form action="{% url 'cart:cart_remove' painting.id %}" method="post">
                    <input type="submit" value="Remove">
                    {% csrf_token %}
                </form>
            </td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="2"></td>
            <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
        </tbody>
    </table>
    {% if most_view %}
    <div class="recommendations cart">
        <h3>Популярное</h3>
        {% for p in most_view %}
        <div class="item">
            <a href="{{ p.get_absolute_url }}">
                <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
            </a>
            <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <p class="text-right">
        <a href="{% url 'shop:painting_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'order:order_create' %}" class="button">
            Checkout
        </a>
    </p>
</div>
{% endblock %}

order/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}
  <h1>Checkout</h1>
  <div class="order-info">
    <h3>Ваш заказ:</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.painting.name }}
          <span>{{ item.price }} руб.</span>
        </li>
      {% endfor %}
    </ul>
    <p>Сумма: {{ cart.get_total_price }} руб.</p>
  </div>
  <form method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
  </form>
{% endblock %}

order/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}
  <h1>Thank you</h1>
  <p>Your order has been successfully completed. Your order number is
  <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Магазин картин{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">Магазин картин</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
        {% if total_items > 0 %}
        Корзина:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} картин{{ total_items|pluralize:"a,ы" }},
            ${{ cart.get_total_price }}
        </a>
        {% else %}
        Ваша корзина пуста.
        {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

shop/templates/shop/painting/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ painting.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if painting.image %}{{ painting.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ painting.name }}</h1>
    <div class="tags">
        {% for tag in painting.tag.all %}
        <h2>
            <a class="button" href="{{ tag.get_absolute_url }}">
                {{ tag }}
            </a>
        </h2>
        {% endfor %}
    </div>
    <p class="price">${{ painting.price }}</p>
    <form action="{% url 'cart:cart_add' painting.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>
    {{ painting.description|linebreaks }}
    {% if most_view %}
    <div class="recommendations">
        <h3>Популярное</h3>
        {% for m in most_view %}
        <div class="item">
            <a href="{{ m.get_absolute_url }}">
                <img src="{% if m.image %}{{ m.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
            </a>
            <p><a href="{{ m.get_absolute_url }}">{{ m.name }}</a></p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

shop/templates/shop/painting/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if tag %}{{ tag.name }}{% else %}Картины{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Тэги</h3>
    <ul>
      <li {% if not tag %}class="selected"{% endif %}>
        <a href="{% url 'shop:painting_list' %}">Все</a>
      </li>
      {% for t in tags %}
        <li {% if tag.slug == t.slug %}class="selected"{% endif %}>
          <a href="{{ t.get_absolute_url }}">{{ t.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if tag %}{{ tag.name }}{% else %}Картины{% endif %}</h1>
    {% for painting in paintings %}
      <div class="item">
        <a href="{{ painting.get_absolute_url }}">
          <img src="{% if painting.image %}{{ painting.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ painting.get_absolute_url }}">{{ painting.name }}</a>
        <br>
        ${{ painting.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %}